version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: nvm use 14
            - run: npm install
            - run: npm run bootstrap
            - run: npm test         
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo _auth=$NPM_PUBLISH_TOKEN >> .npmrc
            - run: git config user.name $CIRCLE_USERNAME
            - run: npm version patch
            - run: npm publish
workflows:
    build-test-deploy:
      jobs:
        - build-and-test
#         - publish:
#             requires:
#               - build-and-test
        
